name: RSS
on:
  schedule:
    - cron: "10 21 * * *"
  push:

jobs:
  generate_rss:
    runs-on: macOS-latest
    name: Generate RSS
    steps:
      - name: RSS
        id: rss
        uses: 51LR12.github.io/instagram-rss.yml
        with:
          yourInstagram: riverscrounger.media
          listOfInstagrams: amoo._.maleh,amr.tabash,anas.ibrahem1,anas.sham0,anasabudayyah1,anasjamal44
        - name: Commit files
          if: ${{ success() && steps.rss.outputs.RSS_STATUS == 'success' }}
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git commit -am "Updated instagram.json"
            git push
